### ISSUE TITLE
p2-layout-provider does not work with quarkus

### ISSUE THREAD

**Issue by git-asol** [OpenNTF/p2-layout-provider#38]
Hi, 
I stumbled upon following problem: 

- I setup a quarkus-maven project and use the p2-layout-provider to include EMF related dependencies. So far everything works fine. 
- When checking out the project on other machines the maven build fails because `quarkus-bom-quarkus-platform-properties-2.16.0.Final.properties` cannot be read. When deleting the properties file from my m2-repo on my original machine I get the same error.
- The error occurs as soon as I define a p2-repository with the `<layout>p2</layout>` - without even defining a dependency from this repository

The error message I receive is:
`[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:2.16.0.Final:generate-code (default) on project meetinglog: Quarkus code generation phase has failed: Failed to bootstrap application in NORMAL mode: Failed to read properties from /Users/asolbach/.m2/repository/io/quarkus/platform/quarkus-bom-quarkus-platform-properties/2.16.0.Final/quarkus-bom-quarkus-platform-properties-2.16.0.Final.properties -> [Help 1]`

Here my minimal pom (dominated by quarkus dependencies and plugins) to reproduce the error:
```
<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.example.project</groupId>
  <artifactId>project-name</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <properties>
    <compiler-plugin.version>3.10.1</compiler-plugin.version>
    <maven.compiler.release>17</maven.compiler.release>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
    <quarkus.platform.group-id>io.quarkus.platform</quarkus.platform.group-id>
    <quarkus.platform.version>2.16.0.Final</quarkus.platform.version>
    <skipITs>true</skipITs>
    <surefire-plugin.version>3.0.0-M7</surefire-plugin.version>
  </properties>

  <pluginRepositories>
    <!-- the plugin is hosted in OpenNTF's Maven repository -->
    <pluginRepository>
      <id>artifactory.openntf.org</id>
      <name>artifactory.openntf.org</name>
      <url>https://artifactory.openntf.org/openntf</url>
    </pluginRepository>
  </pluginRepositories>

  <repositories>
    <repository>
      <id>local.p2.updatesite</id>   <!-- defines the groupId to be used below -->
      <url>file:///Users/xyz/project/lib/local.p2.updatesite-1.2.3</url>
      <layout>p2</layout>
    </repository>
  </repositories>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>${quarkus.platform.group-id}</groupId>
        <artifactId>${quarkus.platform.artifact-id}</artifactId>
        <version>${quarkus.platform.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-reactive-jsonb</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-arc</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-reactive</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-junit5</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.rest-assured</groupId>
      <artifactId>rest-assured</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.openntf.maven</groupId>
        <artifactId>p2-layout-resolver</artifactId>
        <version>1.6.0</version>
        <extensions>true</extensions>
      </plugin>
      <plugin>
        <groupId>${quarkus.platform.group-id}</groupId>
        <artifactId>quarkus-maven-plugin</artifactId>
        <version>${quarkus.platform.version}</version>
        <extensions>true</extensions>
        <executions>
          <execution>
            <goals>
              <goal>build</goal>
              <goal>generate-code</goal>
              <goal>generate-code-tests</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>${compiler-plugin.version}</version>
        <configuration>
          <compilerArgs>
            <arg>-parameters</arg>
          </compilerArgs>
        </configuration>
      </plugin>
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>${surefire-plugin.version}</version>
        <configuration>
          <systemPropertyVariables>
            <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
            <maven.home>${maven.home}</maven.home>
          </systemPropertyVariables>
        </configuration>
      </plugin>
      <plugin>
        <artifactId>maven-failsafe-plugin</artifactId>
        <version>${surefire-plugin.version}</version>
        <executions>
          <execution>
            <goals>
              <goal>integration-test</goal>
              <goal>verify</goal>
            </goals>
            <configuration>
              <systemPropertyVariables>
                <native.image.path>${project.build.directory}/${project.build.finalName}-runner</native.image.path>
                <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
                <maven.home>${maven.home}</maven.home>
              </systemPropertyVariables>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
  <profiles>
    <profile>
      <id>native</id>
      <activation>
        <property>
          <name>native</name>
        </property>
      </activation>
      <properties>
        <skipITs>false</skipITs>
        <quarkus.package.type>native</quarkus.package.type>
      </properties>
    </profile>
  </profiles>
</project>
```
Regards!

**Comment by git-asol** [comment]
One more observation on that topic:

As a workaround I can add the standard maven repository to the list of repositories. It seems to me that the plugin kicks in when all other dependency are loaded. However, the properties are loaded only later during the build. Here the standard repository is not accessible anymore but replaced by the p2 repository recently used.

**Comment by reckart** [comment]
@git-asol I may be wrong, but normally the p2 repository should not "replace" an existing repository. Are you by any chance using the same ID for multiple repositories?

**Comment by git-asol** [comment]
```
#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Fri Feb 03 10:59:37 CET 2023
file:///Users/xyz/project/lib/local.p2.updatesite-1.2.3/.lastUpdated=1675418377120
```
I´m not that deep into maven - but this is the content of the properties file inside my local maven repository. Here I see the link to my local p2 update site (where surly no quarkus properties file can be found). Thus, I interpreted that the default repo was replaced. When adding it manually to the repository list it works properly.

**Comment by reckart** [comment]
AFAIK maven should normally contact all repositories for any artifact it tries to resolve until it finds one - or until none of them contains the artifact.

**Comment by jesse-gallagher** [comment]
I definitely see the same sort of trouble here. If I have a project that does nothing but declare the properties file as a dependency, it's resolved and downloaded successfully. If I have the same dependency in the example project here, clear out the local repo copy, and install that, it "succeeds" but doesn't actually download the properties file.

**Comment by jesse-gallagher** [comment]
I believe I've fixed this in a 1.7.0-SNAPSHOT build that I just pushed up. When you get a chance, could you give that a try? If it works, I can make that a 1.7.0 release.

For future reference for me and anyone else, it appears that the trouble is that the `getLocation` method in the `RepositoryLayout` implementation class was returning `null` for unhandled file types, and this silently short-circuits the resolution process. I changed the `null` paths to return a fake URI instead, which is required by the parent interface.

**Comment by git-asol** [comment]
For me 1.7.0-SNAPSHOT does the trick. Thanks! Looking forward to the non-snapshot release.

**Comment by jesse-gallagher** [comment]
Excellent - glad to hear it! I've pushed 1.7.0 up now, so you should be able to switch to the release build.
