### ISSUE TITLE
OpenNTF's Maven repository not available

### ISSUE THREAD

**Issue by larsk21** [OpenNTF/p2-layout-provider#43]
I noticed today that OpenNTF's Maven repository (https://artifactory.openntf.org/openntf) where the p2-layout-provider is deployed is currently not available.

Is there any information on how long the repository will be down or is it no longer available? I also second issue https://github.com/OpenNTF/p2-layout-provider/issues/39 on publishing to Maven central instead.

**Comment by jesse-gallagher** [comment]
Good question - I'll look into why it's down, since I use it all the time.

**Comment by jesse-gallagher** [comment]
Looks like bouncing the server earlier fixed it.

**Comment by larsk21** [comment]
Works again, thank you :slightly_smiling_face:

**Comment by reckart** [comment]
Going to Maven Central would still be nice though...
